#
# This source file is part of the Schmiedmayer Lab open-source organization
#
# SPDX-FileCopyrightText: 2026 Schmiedmayer Lab and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: REUSE Compliance

on:
  workflow_call:
    inputs:
      runs_on_labels:
        description: |
          JSON-based collection of labels indicating which type of GitHub runner should be chosen.
        required: false
        type: string
        default: '["ubuntu-latest"]'

permissions:
  contents: read

jobs:
  reuse:
    name: REUSE Compliance
    runs-on: ${{ fromJson(inputs.runs_on_labels) }}
    steps:
      - uses: actions/checkout@v7
      - name: REUSE Compliance
        uses: fsfe/reuse-action@v6
